HDA-1973 refactor service actions
hedia-team/shared-workflows pull request #5
Opened 2022-01-26 12:46 UTC by akindo

2022-02-23 10:28 UTC, rikke requested changes

2022-02-23 10:28 UTC, rikke commented on .github/workflows/ci-service.yaml
> +      GIT_CRYPT_KEY:
Not all services needs this, no need to make it required?

2022-02-23 10:28 UTC, rikke commented on .github/workflows/ci-service.yaml
> +      HEDIA_BOT_NPM_TOKEN:
What's the reason for this renaming?

2022-02-23 10:28 UTC, rikke commented on .github/workflows/ci-service.yaml
> +      - run: npm run lint
This is not reflected in the template, and probably not in all repos either, so it will break stuff

2022-02-23 10:28 UTC, rikke commented on .github/workflows/create-release.yaml
> -    if: startsWith(github.head_ref, 'release/') && github.event.pull_request.merged == true
What's the reason to remove this, it should only be done for release branches?

2022-02-23 10:28 UTC, rikke commented on .github/workflows/publish-and-deploy-container.yaml
>  name: Publish and deploy Docker container
Update filename to what's currently on master.

2022-02-23 10:28 UTC, rikke commented on .github/workflows/publish-and-deploy-container.yaml
> -      NPM_TOKEN:
As above, what's the reason the rename this?

2022-02-23 10:28 UTC, rikke commented on .github/workflows/publish-and-deploy-container.yaml
> -    if: github.event.pull_request.merged == true
We only want this run on merge. Is there an alternative way to specify that?

2022-02-23 10:28 UTC, rikke commented on .github/workflows/validate-pr-labels-service.yaml
> -          any_of: feature,feat,fix,test
Sure this won't break stuff?

2022-02-23 12:37 UTC, akindo commented on .github/workflows/ci-service.yaml
> +      GIT_CRYPT_KEY:
Well spotted, will fix this.

2022-02-23 12:40 UTC, akindo commented on .github/workflows/ci-service.yaml
> +      - run: npm run lint
It will be changed everywhere.

2022-02-23 12:42 UTC, akindo commented on .github/workflows/ci-service.yaml
> +      HEDIA_BOT_NPM_TOKEN:
Was to have it be the same name as the calling workflow, but agree NPM_TOKEN is better. :)

2022-02-23 14:01 UTC, akindo commented on .github/workflows/create-release.yaml
> -    if: startsWith(github.head_ref, 'release/') && github.event.pull_request.merged == true
This bit has been moved to the calling workflows to make the workflow more configurable (e. g. the calling workflow can decide the branch name).

2022-02-23 14:04 UTC, akindo commented on .github/workflows/publish-and-deploy-container.yaml
> -    if: github.event.pull_request.merged == true
Unfortunately not. :/

2022-02-23 14:07 UTC, akindo commented on .github/workflows/validate-pr-labels-service.yaml
> -          any_of: feature,feat,fix,test
It didn't during testing. As long as the PR created with a label of feature, fix or test it will pass. But will pay attention to this when creating PRs in the various repos.

2022-02-23 14:08 UTC, akindo commented on .github/workflows/publish-and-deploy-container.yaml
>  name: Publish and deploy Docker container
Thanks, done.

2022-03-04 13:41 UTC, akindo commented on .github/workflows/ci-service.yaml
> +      GIT_CRYPT_KEY:
Workflows for services which don't have any encrypted files will pass the `Decrypt config` stage (which takes 1 sec.). Because the secret is stored as an organization secret it's automatically passed on. However, all repos must be encrypted with the same key for this to work. Believe it's only menarini and service template which use git-crypt, and they're using the same key. I've updated the LastPass item with info:

_Symmetric key to encrypt and decrypt local config secrets for all services. If adding git-crypt to a service, add the service repo name in 'repos-using-git-crypt.txt' found in the zip file. Hedia CLI copies the symmetric key file to the repos listed in the txt file and unlocks them. Further info:
https://github.com/hedia-team/cli/#readme
https://github.com/hedia-team/config/#readme_

2022-03-04 14:21 UTC, akindo commented on .github/workflows/integration-tests.yaml
> +      - run: npm run migration:run-dev
The idea with `run-dev` is to provide the ability to have a migration which both creates a schema and inserts required test data.

2022-03-07 08:14 UTC, rikke commented on .github/workflows/integration-tests.yaml
> +      - run: npm run migration:run-dev
But this enforces all projects to have that script, whether they need it or not. I think it would be cleaner if database migrations only contains actual migrations (that is only DDL additions and updates), and let test data be inserted in test setup. In this way it might also be more transparent what is going on in the test.

2022-03-07 08:14 UTC, rikke commented on .github/workflows/publish-and-deploy-service.yaml
> +# Builds and publishes Docker image to ghcr.io and Heroku Container Registry, and deploys container to Heroku app.
Which yaml extension do you use to get this formatting?

2022-03-07 08:15 UTC, rikke approved these changes

2022-03-07 08:27 UTC, rikke commented on .github/workflows/integration-tests.yaml
> +      - run: npm run migration:run-dev
But this enforces all projects to have that script, whether they need it or not. I think it would be cleaner if database migrations only contains actual migrations (that is only DDL additions and updates), and let test data be inserted in test setup. In this way it might also be more transparent what is going on in the test.

2022-03-07 08:28 UTC, rikke commented on .github/workflows/publish-and-deploy-service.yaml
> +# Builds and publishes Docker image to ghcr.io and Heroku Container Registry, and deploys container to Heroku app.
Which yaml extension do you use to get this formatting?

2022-03-07 08:50 UTC, akindo commented on .github/workflows/integration-tests.yaml
> +      - run: npm run migration:run-dev
Good idea.

2022-03-07 09:21 UTC, akindo commented on .github/workflows/publish-and-deploy-service.yaml
> +# Builds and publishes Docker image to ghcr.io and Heroku Container Registry, and deploys container to Heroku app.
Just manually formatted the comments to 120 characters per line (in this case 124, so the "to" wouldn't be on it's own in a third line).

But did notice your setup auto converts ' to " in the YAML files (we prefer backtick over ', and ' over "). I added `.prettierrc` to the root of the repo, I've got Prettier set to format on save. In my setup no auto conversion of " nor ' happens in YAML files (`.prettierrc` has `"singleQuote": false`, but even turning it to true doesn't force conversion of " to ' in YAML files it seems).

I have the YAML RedHat extension installed, which provides the setting in the screenshot below. Tried enabling it to see if it would auto convert " to ', but didn't work either. But perhaps see if you can get your setup to not convert ' to "?
![image](https://user-images.githubusercontent.com/977789/156999754-2665b718-eb95-4d15-8b41-434c079029be.png)

2022-03-07 09:36 UTC, rikke commented on .github/workflows/publish-and-deploy-service.yaml
> +# Builds and publishes Docker image to ghcr.io and Heroku Container Registry, and deploys container to Heroku app.
What is the issue with using double quotes?

The yaml language server implementation by RedHat seems to be the default, so we could just use that as the formatting basis? No need for manually formatting then.

2022-03-07 10:18 UTC, akindo commented on .github/workflows/publish-and-deploy-service.yaml
> +# Builds and publishes Docker image to ghcr.io and Heroku Container Registry, and deploys container to Heroku app.
No issue. Some might find single quote cleaner, and requires only one keystroke on a Danish keyboard vs. two for double. 😁 But agree we should have the same formatting setup, good suggestion.

2022-03-07 10:21 UTC, merged